version: '3'

services:
  btcup:
    image: btcup:latest
    build: .
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - internal

  influx:
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb
    env_file:
      - .env
    networks:
      - internal

volumes:
  influx_data:

networks:
  internal:
