name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - name: Lint with flake8
        run: |
          flake8 app tests

      - name: Test with pytest
        run: |
          pytest

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(python -c 'from app import __version__; print(__version__)')
          echo "::set-output name=VERSION::$VERSION"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/currency-app:${{ steps.extract_version.outputs.VERSION }}
          build-args: |
            VERSION=${{ steps.extract_version.outputs.VERSION }}

  tag:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Git tag
        id: tag_version
        run: |
          VERSION=$(python -c 'from app import __version__; print(__version__)')
          git tag -a "v$VERSION" -m "Release version $VERSION"
          git push origin "v$VERSION"
